Option Explicit

' v1.6 VBE-safe source: BOM-free, CRLF, no module Attribute lines.
' Replace the existing standard module code with this source.

'============================================================
' Zabbix 6.0 Template YAML Importer v1.6 (ASCII-only source)
'   - No Japanese literal in this module (encoding safe)
'   - Japanese output is generated by U() with Unicode code points
'   - Output columns A..Q (17)
'       A Template / B LLD name / C LLD status
'       D Item name / E Item status / F Item type / G Delay
'       H History / I Trends / J Item tags
'       K Trigger name / L Trigger status / M Severity
'       N Trigger expression / O Trigger tags
'       P Item description / Q Trigger description
'   - v1.6: parses scalar values only for fields that are actually exported
'           to Excel. Complex preprocessing/script YAML is skipped entirely.
'   - v1.6: exports discovery-rule-only templates even when the LLD has no
'           item prototypes. The row contains Template + LLD name/status and
'           '-' in Item/Trigger columns.
'   - v1.6: fixes inline list properties (for example '- tag: component').
'   - Keeps v1.3 fixes for Zabbix 6.0 indentation, trigger prototype layouts,
'           multiline quoted scalars, and blank error reason handling.
'============================================================

Private Const TARGET_SHEET_PREFIX As String = "Kubernetes"
Private Const DATA_START_ROW As Long = 4
Private Const LAST_COL As Long = 17
Private Const LAST_COL_LETTER As String = "Q"

'============================================================
' Unicode helper
'============================================================

Private Function U(ByVal hexList As String) As String
    Dim a() As String, i As Long, code As Long, s As String
    a = Split(Trim$(hexList), " ")
    For i = LBound(a) To UBound(a)
        If Len(a(i)) > 0 Then
            code = CLng("&H" & a(i))
            If code > 32767 Then code = code - 65536
            s = s & ChrW$(code)
        End If
    Next i
    U = s
End Function

Public Sub SelfTestJapanese()
    MsgBox "ENABLED  -> " & StatusJa("ENABLED") & vbCrLf & _
           "DISABLED -> " & StatusJa("DISABLED") & vbCrLf & _
           "ZABBIX_ACTIVE -> " & ItemTypeJa("ZABBIX_ACTIVE") & vbCrLf & _
           "DEPENDENT     -> " & ItemTypeJa("DEPENDENT") & vbCrLf & _
           "DISASTER -> " & SeverityJa("DISASTER") & vbCrLf & _
           "HIGH     -> " & SeverityJa("HIGH"), _
           vbInformation, "Zabbix YAML Importer - self test"
End Sub

'============================================================
' Sheet resolver
'============================================================

Private Function TargetSheet() As Worksheet
    Dim ws As Worksheet
    For Each ws In ThisWorkbook.Worksheets
        If LCase$(Left$(ws.Name, Len(TARGET_SHEET_PREFIX))) = LCase$(TARGET_SHEET_PREFIX) Then
            Set TargetSheet = ws
            Exit Function
        End If
    Next ws
    Err.Raise vbObjectError + 1100, , _
        "Target sheet not found. Sheet name must start with '" & TARGET_SHEET_PREFIX & "'."
End Function

'============================================================
' Public entry points
'============================================================

Public Sub SetupImportButton()
    Dim ws As Worksheet
    Dim btn As Button
    Dim shp As Object
    Dim leftPos As Double, topPos As Double, btnWidth As Double, btnHeight As Double

    On Error GoTo EH
    Set ws = TargetSheet()

    On Error Resume Next
    For Each shp In ws.Buttons
        If shp.Name = "btnZabbixYamlImport" Then shp.Delete
    Next shp
    On Error GoTo EH

    With ws.Range("B1:C1")
        leftPos = .Left + 2
        topPos = .Top + 2
        btnWidth = .Width - 4
        btnHeight = .Height - 4
    End With

    Set btn = ws.Buttons.Add(leftPos, topPos, btnWidth, btnHeight)
    With btn
        .Name = "btnZabbixYamlImport"
        .Caption = "Zabbix YAML Import"
        .OnAction = "'" & ThisWorkbook.Name & "'!ImportZabbixYaml"
        .Font.Bold = True
        .Font.Size = 10
    End With

    MsgBox "Import button was placed on B1:C1.", vbInformation, "Zabbix YAML Importer"
    Exit Sub
EH:
    MsgBox "Setup failed." & vbCrLf & Err.Description, vbExclamation, "Zabbix YAML Importer"
End Sub

Public Sub ImportZabbixYaml()
    Dim selectedFile As Variant
    Dim yamlText As String
    Dim templates As Collection
    Dim outRows As Collection
    Dim ws As Worksheet

    Dim templateCount As Long, itemCount As Long, prototypeCount As Long
    Dim triggerCount As Long, unmatchedPrototypeTriggerCount As Long
    Dim firstOutputRow As Long, lastOutputRow As Long, outputCount As Long

    Dim oldScreenUpdating As Boolean
    Dim oldEnableEvents As Boolean
    Dim oldCalculation As XlCalculation
    Dim stateSaved As Boolean

    Dim errNumber As Long
    Dim errDescription As String
    Dim errSource As String

    On Error GoTo EH

    selectedFile = Application.GetOpenFilename( _
        FileFilter:="Zabbix YAML (*.yaml;*.yml),*.yaml;*.yml", _
        Title:="Select Zabbix 6.0 template export YAML")
    If VarType(selectedFile) = vbBoolean Then Exit Sub

    oldScreenUpdating = Application.ScreenUpdating
    oldEnableEvents = Application.EnableEvents
    oldCalculation = Application.Calculation
    stateSaved = True

    Application.ScreenUpdating = False
    Application.EnableEvents = False
    Application.Calculation = xlCalculationManual
    Application.StatusBar = "Reading Zabbix YAML ..."

    yamlText = ReadUtf8File(CStr(selectedFile))
    ValidateZabbix60 yamlText

    Set templates = ParseZabbixYaml(yamlText)
    If templates.Count = 0 Then
        Err.Raise vbObjectError + 1101, "ParseZabbixYaml", _
                  "No 'templates' found in the YAML. Check Zabbix 6.0 export structure."
    End If

    Application.StatusBar = "Building rows ..."
    Set outRows = BuildOutputRows(templates, templateCount, itemCount, _
                                  prototypeCount, triggerCount, unmatchedPrototypeTriggerCount)

    outputCount = outRows.Count
    If outputCount = 0 Then
        Err.Raise vbObjectError + 1102, "BuildOutputRows", _
                  "No item / item prototype / discovery rule to export."
    End If

    Set ws = TargetSheet()
    firstOutputRow = NextAppendRow(ws)
    lastOutputRow = firstOutputRow + outputCount - 1

    Application.StatusBar = "Writing " & outputCount & " rows ..."
    WriteRows ws, outRows, firstOutputRow, lastOutputRow

    Application.StatusBar = False
    Application.ScreenUpdating = oldScreenUpdating
    Application.EnableEvents = oldEnableEvents
    Application.Calculation = oldCalculation

    Dim msg As String
    msg = "Import completed." & vbCrLf & vbCrLf & _
          "File       : " & Dir(CStr(selectedFile)) & vbCrLf & _
          "Templates  : " & templateCount & vbCrLf & _
          "Items      : " & itemCount & vbCrLf & _
          "Prototypes : " & prototypeCount & vbCrLf & _
          "Triggers   : " & triggerCount & vbCrLf & _
          "Rows added : " & outputCount & "  (row " & firstOutputRow & " - " & lastOutputRow & ")"

    If unmatchedPrototypeTriggerCount > 0 Then
        msg = msg & vbCrLf & vbCrLf & "Note: " & unmatchedPrototypeTriggerCount & _
              " trigger prototype(s) not matched to an item prototype."
    End If

    MsgBox msg, vbInformation, "Zabbix YAML Importer"
    Exit Sub

EH:
    ' Preserve the original error BEFORE any cleanup statements.
    errNumber = Err.Number
    errDescription = Err.Description
    errSource = Err.Source

    If Len(errDescription) = 0 Then
        errDescription = "VBA error " & CStr(errNumber)
    End If
    If Len(errSource) = 0 Then
        errSource = "ZabbixYamlImporter"
    End If

    On Error Resume Next
    Application.StatusBar = False
    If stateSaved Then
        Application.ScreenUpdating = oldScreenUpdating
        Application.EnableEvents = oldEnableEvents
        Application.Calculation = oldCalculation
    End If
    On Error GoTo 0

    MsgBox "Import aborted." & vbCrLf & vbCrLf & _
           "Reason: " & errDescription & vbCrLf & _
           "Source: " & errSource & vbCrLf & _
           "Error No.: " & CStr(errNumber), _
           vbExclamation, "Zabbix YAML Importer"
End Sub

'============================================================
' YAML read / validation
'============================================================

Private Function ReadUtf8File(ByVal filePath As String) As String
    Dim stm As Object
    Dim errDescription As String
    Dim errNumber As Long

    On Error GoTo EH
    Set stm = CreateObject("ADODB.Stream")
    With stm
        .Type = 2
        .Charset = "utf-8"
        .Open
        .LoadFromFile filePath
        ReadUtf8File = .ReadText(-1)
        .Close
    End With
    Exit Function

EH:
    errNumber = Err.Number
    errDescription = Err.Description

    On Error Resume Next
    If Not stm Is Nothing Then stm.Close
    On Error GoTo 0

    If Len(errDescription) = 0 Then errDescription = "VBA error " & CStr(errNumber)
    Err.Raise vbObjectError + 1110, "ReadUtf8File", _
              "Failed to read UTF-8 YAML: " & errDescription
End Function

Private Sub ValidateZabbix60(ByVal yamlText As String)
    Dim normalized As String, lines() As String
    Dim i As Long, s As String
    Dim key As String, value As String
    Dim foundRoot As Boolean, foundVersion As Boolean

    normalized = Replace(yamlText, vbCrLf, vbLf)
    normalized = Replace(normalized, vbCr, vbLf)
    lines = Split(normalized, vbLf)

    For i = LBound(lines) To UBound(lines)
        s = Trim$(RemoveBom(lines(i)))
        If s = "zabbix_export:" Then
            foundRoot = True
        ElseIf LeadingSpaces(RemoveBom(lines(i))) = 2 Then
            If SplitKeyValue(s, key, value) Then
                If LCase$(key) = "version" Then
                    foundVersion = True
                    value = ParseScalar(value)
                    If value <> "6.0" Then
                        Err.Raise vbObjectError + 1111, , _
                            "This macro supports Zabbix 6.0 only. YAML version is """ & value & """."
                    End If
                    Exit For
                End If
            End If
        End If
    Next i

    If Not foundRoot Then Err.Raise vbObjectError + 1112, , "'zabbix_export:' not found."
    If Not foundVersion Then Err.Raise vbObjectError + 1113, , "'zabbix_export.version' not found."
End Sub

'============================================================
' Parser
'============================================================

Private Function ParseZabbixYaml(ByVal yamlText As String) As Collection
    Dim templates As New Collection
    Dim normalized As String, lines() As String
    Dim sections(0 To 200) As String

    Dim curTemplate As Object, curItem As Object, curLld As Object
    Dim curProto As Object, curTrigger As Object, curTag As Object
    Dim templateIndent As Long, itemIndent As Long, lldIndent As Long
    Dim protoIndent As Long, triggerIndent As Long, tagIndent As Long

    Dim i As Long, j As Long
    Dim raw As String, content As String
    Dim indent As Long
    Dim parentSection As String, parentSectionIndent As Long
    Dim remainder As String, key As String, value As String
    Dim isListItem As Boolean, createdRelevantObject As Boolean

    normalized = Replace(yamlText, vbCrLf, vbLf)
    normalized = Replace(normalized, vbCr, vbLf)
    lines = Split(normalized, vbLf)

    i = LBound(lines)

    Do While i <= UBound(lines)
        raw = RemoveBom(lines(i))

        If Trim$(raw) = vbNullString Then
            i = i + 1
            GoTo ContinueLoop
        End If

        indent = LeadingSpaces(raw)
        content = Mid$(raw, indent + 1)

        If Left$(Trim$(content), 1) = "#" Then
            i = i + 1
            GoTo ContinueLoop
        End If

        ' Close contexts when indentation returns to the object level or above.
        If Not curTag Is Nothing Then
            If indent <= tagIndent Then Set curTag = Nothing
        End If
        If Not curTrigger Is Nothing Then
            If indent <= triggerIndent Then Set curTrigger = Nothing
        End If
        If Not curProto Is Nothing Then
            If indent <= protoIndent Then Set curProto = Nothing
        End If
        If Not curItem Is Nothing Then
            If indent <= itemIndent Then Set curItem = Nothing
        End If
        If Not curLld Is Nothing Then
            If indent <= lldIndent Then Set curLld = Nothing
        End If
        If Not curTemplate Is Nothing Then
            If indent <= templateIndent Then Set curTemplate = Nothing
        End If

        isListItem = False
        remainder = vbNullString

        If Trim$(content) = "-" Then
            isListItem = True
        ElseIf Left$(Trim$(content), 2) = "- " Then
            isListItem = True
            remainder = Mid$(Trim$(content), 3)
        End If

        If isListItem Then
            ' Zabbix 6.0 export YAML places "- item" at the SAME indentation
            ' as the collection key (templates/items/discovery_rules/etc.).
            parentSection = NearestSection(sections, indent, parentSectionIndent)
            createdRelevantObject = False

            Select Case LCase$(parentSection)
                Case "templates"
                    If parentSectionIndent = 2 Then
                        Set curTemplate = NewTemplateObject()
                        curTemplate("_indent") = indent
                        templates.Add curTemplate
                        templateIndent = indent
                        createdRelevantObject = True
                    End If

                Case "items"
                    If parentSectionIndent = 4 And Not curTemplate Is Nothing Then
                        Set curItem = NewItemObject()
                        curItem("_indent") = indent
                        ObjectCollection(curTemplate, "items").Add curItem
                        itemIndent = indent
                        createdRelevantObject = True
                    End If

                Case "discovery_rules"
                    If parentSectionIndent = 4 And Not curTemplate Is Nothing Then
                        Set curLld = NewLldObject()
                        curLld("_indent") = indent
                        ObjectCollection(curTemplate, "llds").Add curLld
                        lldIndent = indent
                        createdRelevantObject = True
                    End If

                Case "item_prototypes"
                    If parentSectionIndent = 6 And Not curLld Is Nothing Then
                        Set curProto = NewItemObject()
                        curProto("_indent") = indent
                        ObjectCollection(curLld, "item_prototypes").Add curProto
                        protoIndent = indent
                        createdRelevantObject = True
                    End If

                Case "triggers"
                    If parentSectionIndent = 6 And Not curItem Is Nothing Then
                        Set curTrigger = NewTriggerObject()
                        curTrigger("_indent") = indent
                        curTrigger("owner_key") = DGet(curItem, "key", vbNullString)
                        ObjectCollection(curItem, "triggers").Add curTrigger
                        triggerIndent = indent
                        createdRelevantObject = True
                    End If

                Case "trigger_prototypes"
                    ' Zabbix 6.0 exports trigger prototypes in two layouts:
                    '   1) under an item prototype (section indent 8)
                    '   2) directly under a discovery rule (section indent 6)
                    If Not curLld Is Nothing Then
                        If parentSectionIndent = 8 And Not curProto Is Nothing Then
                            Set curTrigger = NewTriggerObject()
                            curTrigger("_indent") = indent
                            curTrigger("owner_key") = DGet(curProto, "key", vbNullString)
                            ObjectCollection(curLld, "trigger_prototypes").Add curTrigger
                            triggerIndent = indent
                            createdRelevantObject = True
                        ElseIf parentSectionIndent = 6 Then
                            Set curTrigger = NewTriggerObject()
                            curTrigger("_indent") = indent
                            ObjectCollection(curLld, "trigger_prototypes").Add curTrigger
                            triggerIndent = indent
                            createdRelevantObject = True
                        End If
                    End If

                Case "tags"
                    Set curTag = NewTagObject()
                    curTag("_indent") = indent

                    If Not curTrigger Is Nothing And triggerIndent < indent Then
                        ObjectCollection(curTrigger, "tags").Add curTag
                        tagIndent = indent
                        createdRelevantObject = True
                    ElseIf Not curProto Is Nothing And protoIndent < indent Then
                        ObjectCollection(curProto, "tags").Add curTag
                        tagIndent = indent
                        createdRelevantObject = True
                    ElseIf Not curItem Is Nothing And itemIndent < indent Then
                        ObjectCollection(curItem, "tags").Add curTag
                        tagIndent = indent
                        createdRelevantObject = True
                    Else
                        Set curTag = Nothing
                    End If
            End Select

            If createdRelevantObject And Len(remainder) > 0 Then
                If SplitKeyValue(remainder, key, value) Then
                    ' A property written on the same physical line as a list marker
                    ' (for example "- tag: component") is logically two columns
                    ' deeper than the list indentation. Use that logical indentation
                    ' for direct-property checks and multiline scalar boundaries.
                    If ShouldReadProperty(curTemplate, curItem, curLld, curProto, _
                                          curTrigger, curTag, indent + 2, key) Then
                        value = ReadYamlScalar(lines, i, indent + 2, value)
                        ApplyProperty curTemplate, curItem, curLld, curProto, curTrigger, curTag, _
                                      indent + 2, key, value
                    End If
                End If
            End If

            i = i + 1
            GoTo ContinueLoop
        End If

        If SplitKeyValue(content, key, value) Then
            If Len(Trim$(value)) = 0 Then
                For j = indent To 200
                    sections(j) = vbNullString
                Next j
                sections(indent) = LCase$(Trim$(key))
                i = i + 1
                GoTo ContinueLoop
            End If

            ' IMPORTANT: Do not parse every YAML scalar. Zabbix templates contain
            ' complex quoted JavaScript, preprocessing parameters, graph data,
            ' overrides, host prototypes, and other values that are not represented
            ' by this Excel sheet. Parsing those values was the cause of false
            ' "Unterminated quoted YAML scalar" errors. Parse only direct fields
            ' that this workbook actually imports.
            If ShouldReadProperty(curTemplate, curItem, curLld, curProto, _
                                  curTrigger, curTag, indent, key) Then
                value = ReadYamlScalar(lines, i, indent, value)

                ApplyProperty curTemplate, curItem, curLld, curProto, curTrigger, curTag, _
                              indent, key, value
            End If
        End If

        i = i + 1

ContinueLoop:
    Loop

    Set ParseZabbixYaml = templates
End Function

Private Function ShouldReadProperty( _
    ByVal curTemplate As Object, ByVal curItem As Object, ByVal curLld As Object, _
    ByVal curProto As Object, ByVal curTrigger As Object, ByVal curTag As Object, _
    ByVal indent As Long, ByVal key As String) As Boolean

    key = LCase$(Trim$(key))

    ' Mirror ApplyProperty, but run BEFORE ReadYamlScalar. This prevents the
    ' parser from touching complex YAML values that are irrelevant to Excel.
    If Not curTag Is Nothing Then
        If indent = ObjectIndent(curTag) + 2 Then
            If key = "tag" Or key = "value" Then
                ShouldReadProperty = True
                Exit Function
            End If
        End If
    End If

    If Not curTrigger Is Nothing Then
        If indent = ObjectIndent(curTrigger) + 2 Then
            Select Case key
                Case "expression", "name", "status", "priority", "description"
                    ShouldReadProperty = True
            End Select
            Exit Function
        End If
    End If

    If Not curProto Is Nothing Then
        If indent = ObjectIndent(curProto) + 2 Then
            Select Case key
                Case "name", "type", "key", "delay", "history", "trends", "status", "description"
                    ShouldReadProperty = True
            End Select
            Exit Function
        End If
    End If

    If Not curItem Is Nothing Then
        If indent = ObjectIndent(curItem) + 2 Then
            Select Case key
                Case "name", "type", "key", "delay", "history", "trends", "status", "description"
                    ShouldReadProperty = True
            End Select
            Exit Function
        End If
    End If

    If Not curLld Is Nothing Then
        If indent = ObjectIndent(curLld) + 2 Then
            If key = "name" Or key = "status" Then
                ShouldReadProperty = True
                Exit Function
            End If
        End If
    End If

    If Not curTemplate Is Nothing Then
        If indent = ObjectIndent(curTemplate) + 2 Then
            If key = "template" Or key = "name" Then
                ShouldReadProperty = True
            End If
        End If
    End If
End Function

Private Sub ApplyProperty( _
    ByVal curTemplate As Object, ByVal curItem As Object, ByVal curLld As Object, _
    ByVal curProto As Object, ByVal curTrigger As Object, ByVal curTag As Object, _
    ByVal indent As Long, ByVal key As String, ByVal value As String)

    key = LCase$(Trim$(key))

    ' Only accept direct properties of the current object. This prevents
    ' nested preprocessing/parameters/etc. from overwriting item fields.
    If Not curTag Is Nothing Then
        If indent = ObjectIndent(curTag) + 2 Then
            If key = "tag" Or key = "value" Then
                curTag(key) = value
                Exit Sub
            End If
        End If
    End If

    If Not curTrigger Is Nothing Then
        If indent = ObjectIndent(curTrigger) + 2 Then
            Select Case key
                Case "expression", "name", "status", "priority", "description"
                    curTrigger(key) = value
            End Select
            Exit Sub
        End If
    End If

    If Not curProto Is Nothing Then
        If indent = ObjectIndent(curProto) + 2 Then
            ApplyItemField curProto, key, value
            Exit Sub
        End If
    End If

    If Not curItem Is Nothing Then
        If indent = ObjectIndent(curItem) + 2 Then
            ApplyItemField curItem, key, value
            Exit Sub
        End If
    End If

    If Not curLld Is Nothing Then
        If indent = ObjectIndent(curLld) + 2 Then
            Select Case key
                Case "name", "status"
                    curLld(key) = value
            End Select
            Exit Sub
        End If
    End If

    If Not curTemplate Is Nothing Then
        If indent = ObjectIndent(curTemplate) + 2 Then
            Select Case key
                Case "template", "name"
                    curTemplate(key) = value
            End Select
        End If
    End If
End Sub

Private Sub ApplyItemField(ByVal item As Object, ByVal key As String, ByVal value As String)
    Select Case key
        Case "name", "type", "key", "delay", "history", "trends", "status", "description"
            item(key) = value
    End Select
End Sub

'============================================================
' Object factories
'============================================================

Private Function NewDict() As Object
    Dim d As Object
    Set d = CreateObject("Scripting.Dictionary")
    d.CompareMode = vbTextCompare
    Set NewDict = d
End Function

Private Function NewTemplateObject() As Object
    Dim d As Object, c As Collection
    Set d = NewDict()
    d.Add "template", vbNullString
    d.Add "name", vbNullString
    Set c = New Collection: d.Add "items", c
    Set c = New Collection: d.Add "llds", c
    Set NewTemplateObject = d
End Function

Private Function NewItemObject() As Object
    Dim d As Object, c As Collection
    Set d = NewDict()
    d.Add "name", vbNullString
    d.Add "type", vbNullString
    d.Add "key", vbNullString
    d.Add "delay", vbNullString
    d.Add "history", vbNullString
    d.Add "trends", vbNullString
    d.Add "status", vbNullString
    d.Add "description", vbNullString
    Set c = New Collection: d.Add "tags", c
    Set c = New Collection: d.Add "triggers", c
    Set NewItemObject = d
End Function

Private Function NewLldObject() As Object
    Dim d As Object, c As Collection
    Set d = NewDict()
    d.Add "name", vbNullString
    d.Add "status", vbNullString
    Set c = New Collection: d.Add "item_prototypes", c
    Set c = New Collection: d.Add "trigger_prototypes", c
    Set NewLldObject = d
End Function

Private Function NewTriggerObject() As Object
    Dim d As Object, c As Collection
    Set d = NewDict()
    d.Add "expression", vbNullString
    d.Add "name", vbNullString
    d.Add "status", vbNullString
    d.Add "priority", vbNullString
    d.Add "description", vbNullString
    d.Add "owner_key", vbNullString
    Set c = New Collection: d.Add "tags", c
    Set NewTriggerObject = d
End Function

Private Function NewTagObject() As Object
    Dim d As Object
    Set d = NewDict()
    d.Add "tag", vbNullString
    d.Add "value", vbNullString
    Set NewTagObject = d
End Function

Private Function ObjectCollection(ByVal d As Object, ByVal key As String) As Collection
    Set ObjectCollection = d(key)
End Function

'============================================================
' Output generation
'============================================================

Private Function BuildOutputRows( _
    ByVal templates As Collection, _
    ByRef templateCount As Long, ByRef itemCount As Long, _
    ByRef prototypeCount As Long, ByRef triggerCount As Long, _
    ByRef unmatchedPrototypeTriggerCount As Long) As Collection

    Dim result As New Collection
    Dim t As Object, item As Object, lld As Object, proto As Object, trig As Object
    Dim items As Collection, llds As Collection
    Dim allTriggers As Collection, matches As Collection
    Dim trigProtos As Collection, protos As Collection
    Dim templateName As String
    Dim seenTriggers As Object, sig As String
    Dim matchedAny As Boolean

    For Each t In templates
        templateCount = templateCount + 1
        templateName = DGet(t, "template", vbNullString)
        If Len(templateName) = 0 Then templateName = DGet(t, "name", vbNullString)

        Set items = ObjectCollection(t, "items")
        itemCount = itemCount + items.Count

        Set allTriggers = New Collection
        Set seenTriggers = NewDict()

        For Each item In items
            For Each trig In ObjectCollection(item, "triggers")
                sig = TriggerSignature(trig)
                If Not seenTriggers.Exists(sig) Then
                    seenTriggers.Add sig, True
                    allTriggers.Add trig
                    triggerCount = triggerCount + 1
                End If
            Next trig
        Next item

        For Each item In items
            Set matches = MatchingTriggersForItem(allTriggers, templateName, DGet(item, "key", vbNullString))
            If matches.Count = 0 Then
                result.Add BuildRow(templateName, Nothing, item, Nothing)
            Else
                For Each trig In matches
                    result.Add BuildRow(templateName, Nothing, item, trig)
                Next trig
            End If
        Next item

        Set llds = ObjectCollection(t, "llds")

        For Each lld In llds
            Set protos = ObjectCollection(lld, "item_prototypes")
            Set trigProtos = ObjectCollection(lld, "trigger_prototypes")

            prototypeCount = prototypeCount + protos.Count
            triggerCount = triggerCount + trigProtos.Count

            ' LLD-only templates (for example host discovery rules) have no
            ' item_prototypes. They are still valid monitoring-design objects
            ' and must be exported as one row per discovery rule.
            If protos.Count = 0 Then
                result.Add BuildRow(templateName, lld, Nothing, Nothing)
            End If

            For Each proto In protos
                Set matches = MatchingTriggersForItem(trigProtos, templateName, DGet(proto, "key", vbNullString))
                If matches.Count = 0 Then
                    result.Add BuildRow(templateName, lld, proto, Nothing)
                Else
                    For Each trig In matches
                        result.Add BuildRow(templateName, lld, proto, trig)
                    Next trig
                End If
            Next proto

            For Each trig In trigProtos
                matchedAny = False
                For Each proto In protos
                    If TriggerReferencesItem(DGet(trig, "expression", vbNullString), _
                                             templateName, DGet(proto, "key", vbNullString)) Then
                        matchedAny = True
                        Exit For
                    End If
                Next proto
                If Not matchedAny Then unmatchedPrototypeTriggerCount = unmatchedPrototypeTriggerCount + 1
            Next trig
        Next lld
    Next t

    Set BuildOutputRows = result
End Function

Private Function MatchingTriggersForItem( _
    ByVal triggers As Collection, ByVal templateName As String, _
    ByVal itemKey As String) As Collection

    Dim result As New Collection
    Dim trig As Object
    Dim ownerKey As String

    If Len(itemKey) = 0 Then
        Set MatchingTriggersForItem = result
        Exit Function
    End If

    For Each trig In triggers
        ownerKey = DGet(trig, "owner_key", vbNullString)
        If TriggerReferencesItem(DGet(trig, "expression", vbNullString), templateName, itemKey) _
           Or (Len(ownerKey) > 0 And ownerKey = itemKey) Then
            result.Add trig
        End If
    Next trig

    Set MatchingTriggersForItem = result
End Function

Private Function TriggerReferencesItem( _
    ByVal expression As String, ByVal templateName As String, _
    ByVal itemKey As String) As Boolean

    Dim needle As String
    If Len(expression) = 0 Or Len(itemKey) = 0 Then Exit Function

    needle = "/" & templateName & "/" & itemKey
    If InStr(1, expression, needle, vbBinaryCompare) > 0 Then
        TriggerReferencesItem = True
        Exit Function
    End If

    If InStr(1, expression, "//" & itemKey, vbBinaryCompare) > 0 Then
        TriggerReferencesItem = True
    End If
End Function

Private Function BuildRow( _
    ByVal templateName As String, ByVal lld As Object, _
    ByVal item As Object, ByVal trig As Object) As Variant

    Dim row(1 To LAST_COL) As Variant

    row(1) = DashIfBlank(templateName)

    If lld Is Nothing Then
        row(2) = "-"
        row(3) = "-"
    Else
        row(2) = DashIfBlank(DGet(lld, "name", vbNullString))
        row(3) = StatusJa(DGet(lld, "status", vbNullString))
    End If

    If item Is Nothing Then
        row(4) = "-": row(5) = "-": row(6) = "-": row(7) = "-"
        row(8) = "-": row(9) = "-": row(10) = "-"
        row(16) = "-"
    Else
        row(4) = DashIfBlank(DGet(item, "name", vbNullString))
        row(5) = StatusJa(DGet(item, "status", vbNullString))
        row(6) = ItemTypeJa(DGet(item, "type", vbNullString))
        row(7) = ItemDelay(item)
        row(8) = DefaultIfBlank(DGet(item, "history", vbNullString), "90d")
        row(9) = DefaultIfBlank(DGet(item, "trends", vbNullString), "365d")
        row(10) = TagsText(ObjectCollection(item, "tags"))
        row(16) = DashIfBlank(CleanText(DGet(item, "description", vbNullString)))
    End If

    If trig Is Nothing Then
        row(11) = "-": row(12) = "-": row(13) = "-": row(14) = "-": row(15) = "-"
        row(17) = "-"
    Else
        row(11) = DashIfBlank(DGet(trig, "name", vbNullString))
        row(12) = StatusJa(DGet(trig, "status", vbNullString))
        row(13) = SeverityJa(DGet(trig, "priority", vbNullString))
        row(14) = DashIfBlank(DGet(trig, "expression", vbNullString))
        row(15) = TagsText(ObjectCollection(trig, "tags"))
        row(17) = DashIfBlank(CleanText(DGet(trig, "description", vbNullString)))
    End If

    BuildRow = row
End Function

Private Sub WriteRows(ByVal ws As Worksheet, ByVal outRows As Collection, _
                      ByVal firstRow As Long, ByVal lastRow As Long)

    Dim data() As Variant
    Dim i As Long, c As Long
    Dim oneRow As Variant
    Dim baseFormatRow As Long

    If outRows.Count = 0 Then Exit Sub

    ReDim data(1 To outRows.Count, 1 To LAST_COL)

    For i = 1 To outRows.Count
        oneRow = outRows(i)
        For c = 1 To LAST_COL
            data(i, c) = oneRow(c)
        Next c
    Next i

    baseFormatRow = firstRow - 1
    If baseFormatRow < DATA_START_ROW Then baseFormatRow = 0

    If baseFormatRow > 0 Then
        ws.Range("A" & baseFormatRow & ":" & LAST_COL_LETTER & baseFormatRow).Copy
        ws.Range("A" & firstRow & ":" & LAST_COL_LETTER & lastRow).PasteSpecial Paste:=xlPasteFormats
        Application.CutCopyMode = False
        ws.rows(firstRow & ":" & lastRow).RowHeight = ws.rows(baseFormatRow).RowHeight
    End If

    With ws.Range("A" & firstRow & ":" & LAST_COL_LETTER & lastRow)
        .NumberFormat = "@"
        .value = data
    End With
End Sub

Private Function NextAppendRow(ByVal ws As Worksheet) As Long
    Dim lastRow As Long
    lastRow = ws.Cells(ws.rows.Count, "A").End(xlUp).row
    If lastRow < DATA_START_ROW Then
        NextAppendRow = DATA_START_ROW
    Else
        NextAppendRow = lastRow + 1
    End If
End Function

'============================================================
' Display conversions (Japanese via U())
'============================================================

Private Function StatusJa(ByVal statusValue As String) As String
    statusValue = UCase$(Trim$(statusValue))
    If statusValue = "DISABLED" Or statusValue = "1" Then
        StatusJa = U("7121 52B9")                       ' disabled
    Else
        StatusJa = U("6709 52B9")                       ' enabled
    End If
End Function

Private Function ItemTypeJa(ByVal itemType As String) As String
    itemType = UCase$(Trim$(itemType))
    If Len(itemType) = 0 Then itemType = "ZABBIX_PASSIVE"

    Select Case itemType
        Case "ZABBIX_PASSIVE", "0"
            ItemTypeJa = "Zabbix" & U("30A8 30FC 30B8 30A7 30F3 30C8")
        Case "TRAP", "ZABBIX_TRAPPER", "2"
            ItemTypeJa = "Zabbix" & U("30C8 30E9 30C3 30D1 30FC")
        Case "SIMPLE", "3"
            ItemTypeJa = U("30B7 30F3 30D7 30EB 30C1 30A7 30C3 30AF")
        Case "INTERNAL", "5"
            ItemTypeJa = "Zabbix" & U("5185 90E8")
        Case "ZABBIX_ACTIVE", "7"
            ItemTypeJa = "Zabbix" & U("30A8 30FC 30B8 30A7 30F3 30C8 FF08 30A2 30AF 30C6 30A3 30D6 FF09")
        Case "EXTERNAL", "10"
            ItemTypeJa = U("5916 90E8 30C1 30A7 30C3 30AF")
        Case "ODBC", "DB_MONITOR", "11"
            ItemTypeJa = U("30C7 30FC 30BF 30D9 30FC 30B9 30E2 30CB 30BF")
        Case "IPMI", "12"
            ItemTypeJa = "IPMI" & U("30A8 30FC 30B8 30A7 30F3 30C8")
        Case "SSH", "13"
            ItemTypeJa = "SSH" & U("30A8 30FC 30B8 30A7 30F3 30C8")
        Case "TELNET", "14"
            ItemTypeJa = "TELNET" & U("30A8 30FC 30B8 30A7 30F3 30C8")
        Case "CALCULATED", "15"
            ItemTypeJa = U("8A08 7B97")
        Case "JMX", "16"
            ItemTypeJa = "JMX" & U("30A8 30FC 30B8 30A7 30F3 30C8")
        Case "SNMP_TRAP", "17"
            ItemTypeJa = "SNMP" & U("30C8 30E9 30C3 30D7")
        Case "DEPENDENT", "18"
            ItemTypeJa = U("4F9D 5B58 30A2 30A4 30C6 30E0")
        Case "HTTP_AGENT", "19"
            ItemTypeJa = "HTTP" & U("30A8 30FC 30B8 30A7 30F3 30C8")
        Case "SNMP_AGENT", "20"
            ItemTypeJa = "SNMP" & U("30A8 30FC 30B8 30A7 30F3 30C8")
        Case "ITEM_TYPE_SCRIPT", "SCRIPT", "21"
            ItemTypeJa = U("30B9 30AF 30EA 30D7 30C8")
        Case Else
            ItemTypeJa = itemType
    End Select
End Function

Private Function SeverityJa(ByVal severity As String) As String
    severity = UCase$(Trim$(severity))
    If Len(severity) = 0 Then severity = "NOT_CLASSIFIED"

    Select Case severity
        Case "NOT_CLASSIFIED", "0"
            SeverityJa = U("672A 5206 985E")            ' not classified
        Case "INFO", "1"
            SeverityJa = U("60C5 5831")                 ' information
        Case "WARNING", "2"
            SeverityJa = U("8B66 544A")                 ' warning
        Case "AVERAGE", "3"
            SeverityJa = U("8EFD 5EA6")                 ' average
        Case "HIGH", "4"
            SeverityJa = U("91CD 5EA6")                 ' high
        Case "DISASTER", "5"
            SeverityJa = U("81F4 547D 7684")            ' disaster
        Case Else
            SeverityJa = severity
    End Select
End Function

Private Function ItemDelay(ByVal item As Object) As String
    Dim delayValue As String, itemType As String

    delayValue = DGet(item, "delay", vbNullString)
    If Len(delayValue) > 0 Then
        ItemDelay = delayValue
        Exit Function
    End If

    itemType = UCase$(DGet(item, "type", vbNullString))
    Select Case itemType
        Case "TRAP", "ZABBIX_TRAPPER", "SNMP_TRAP", "DEPENDENT", "2", "17", "18"
            ItemDelay = "0"
        Case Else
            ItemDelay = "1m"
    End Select
End Function

Private Function TagsText(ByVal tags As Collection) As String
    Dim tagObj As Object
    Dim parts As String, tagName As String, tagValue As String

    If tags Is Nothing Then
        TagsText = "-"
        Exit Function
    End If

    For Each tagObj In tags
        tagName = DGet(tagObj, "tag", vbNullString)
        tagValue = DGet(tagObj, "value", vbNullString)
        If Len(tagName) > 0 Then
            If Len(parts) > 0 Then parts = parts & ", "
            parts = parts & tagName
            If Len(tagValue) > 0 Then parts = parts & ":" & tagValue
        End If
    Next tagObj

    If Len(parts) = 0 Then parts = "-"
    TagsText = parts
End Function

'============================================================
' YAML scalar helpers
'============================================================

Private Function SplitKeyValue(ByVal text As String, ByRef key As String, ByRef value As String) As Boolean
    Dim p As Long
    p = InStr(1, text, ":", vbBinaryCompare)
    If p <= 0 Then Exit Function
    key = Trim$(Left$(text, p - 1))
    value = Trim$(Mid$(text, p + 1))
    If Len(key) = 0 Then Exit Function
    SplitKeyValue = True
End Function

Private Function ParseScalar(ByVal value As String) As String
    Dim s As String
    s = Trim$(value)

    If s = "null" Or s = "~" Then
        ParseScalar = vbNullString
        Exit Function
    End If

    If Len(s) >= 2 Then
        If Left$(s, 1) = "'" And Right$(s, 1) = "'" Then
            s = Mid$(s, 2, Len(s) - 2)
            s = Replace(s, "''", "'")
            ParseScalar = s
            Exit Function
        End If
        If Left$(s, 1) = """" And Right$(s, 1) = """" Then
            s = Mid$(s, 2, Len(s) - 2)
            s = Replace(s, "\""", """")
            s = Replace(s, "\n", vbLf)
            s = Replace(s, "\r", vbCr)
            s = Replace(s, "\t", vbTab)
            s = Replace(s, "\\", "\")
            ParseScalar = s
            Exit Function
        End If
    End If

    ParseScalar = s
End Function

Private Function IsBlockScalar(ByVal value As String) As Boolean
    Dim s As String
    s = Trim$(value)
    If Len(s) = 0 Then Exit Function
    IsBlockScalar = (Left$(s, 1) = "|" Or Left$(s, 1) = ">")
End Function

Private Function CollectBlockScalar( _
    ByRef lines() As String, ByRef currentIndex As Long, _
    ByVal propertyIndent As Long, ByVal scalarIndicator As String) As String

    Dim j As Long, ind As Long, baseIndent As Long
    Dim raw As String, part As String, result As String
    Dim folded As Boolean, haveBaseIndent As Boolean

    folded = (Left$(Trim$(scalarIndicator), 1) = ">")
    j = currentIndex + 1

    Do While j <= UBound(lines)
        raw = lines(j)

        If Trim$(raw) <> vbNullString Then
            ind = LeadingSpaces(raw)
            If ind <= propertyIndent Then Exit Do

            If Not haveBaseIndent Then
                baseIndent = ind
                haveBaseIndent = True
            End If

            If ind >= baseIndent Then
                part = Mid$(raw, baseIndent + 1)
            Else
                part = Trim$(raw)
            End If

            If Len(result) > 0 Then
                If folded Then
                    result = result & " "
                Else
                    result = result & vbLf
                End If
            End If
            result = result & part
        Else
            If Len(result) > 0 Then result = result & vbLf
        End If

        j = j + 1
    Loop

    currentIndex = j - 1
    CollectBlockScalar = result
End Function

Private Function LeadingSpaces(ByVal text As String) As Long
    Dim i As Long
    For i = 1 To Len(text)
        If Mid$(text, i, 1) <> " " Then
            LeadingSpaces = i - 1
            Exit Function
        End If
    Next i
    LeadingSpaces = Len(text)
End Function

Private Function ReadYamlScalar(ByRef lines() As String, ByRef currentIndex As Long, _
                                ByVal propertyIndent As Long, ByVal rawValue As String) As String
    Dim s As String

    s = rawValue

    If IsBlockScalar(s) Then
        ReadYamlScalar = CollectBlockScalar(lines, currentIndex, propertyIndent, s)
        Exit Function
    End If

    If QuotedScalarNeedsContinuation(s) Then
        s = CollectQuotedScalar(lines, currentIndex, propertyIndent, s)
    End If

    ReadYamlScalar = ParseScalar(s)
End Function

Private Function QuotedScalarNeedsContinuation(ByVal value As String) As Boolean
    Dim s As String, q As String

    s = Trim$(value)
    If Len(s) = 0 Then Exit Function

    q = Left$(s, 1)
    If q <> Chr$(39) And q <> Chr$(34) Then Exit Function

    QuotedScalarNeedsContinuation = Not HasClosingQuote(s, q)
End Function

Private Function HasClosingQuote(ByVal s As String, ByVal q As String) As Boolean
    Dim i As Long, slashCount As Long, j As Long

    If Len(s) < 2 Then Exit Function

    i = 2
    Do While i <= Len(s)
        If Mid$(s, i, 1) = q Then
            If q = Chr$(39) Then
                ' YAML single quote escape is doubled single quote.
                If i < Len(s) And Mid$(s, i + 1, 1) = q Then
                    i = i + 2
                    GoTo ContinueScan
                End If

                HasClosingQuote = True
                Exit Function
            Else
                ' Double quote closes only when it is not escaped by an odd
                ' number of consecutive backslashes.
                slashCount = 0
                j = i - 1
                Do While j >= 1 And Mid$(s, j, 1) = "\"
                    slashCount = slashCount + 1
                    j = j - 1
                Loop

                If (slashCount Mod 2) = 0 Then
                    HasClosingQuote = True
                    Exit Function
                End If
            End If
        End If

        i = i + 1
ContinueScan:
    Loop
End Function

Private Function CollectQuotedScalar( _
    ByRef lines() As String, ByRef currentIndex As Long, _
    ByVal propertyIndent As Long, ByVal initialValue As String) As String

    Dim result As String
    Dim q As String
    Dim j As Long
    Dim raw As String
    Dim ind As Long

    result = initialValue
    q = Left$(Trim$(initialValue), 1)
    j = currentIndex + 1

    Do While j <= UBound(lines)
        raw = lines(j)

        If Trim$(raw) = vbNullString Then
            result = result & vbLf
        Else
            ind = LeadingSpaces(raw)

            If ind <= propertyIndent Then
                Err.Raise vbObjectError + 1120, "CollectQuotedScalar", _
                          "Unterminated quoted YAML scalar near line " & CStr(currentIndex + 1) & "."
            End If

            result = result & vbLf & Trim$(raw)

            If HasClosingQuote(result, q) Then
                currentIndex = j
                CollectQuotedScalar = result
                Exit Function
            End If
        End If

        j = j + 1
    Loop

    Err.Raise vbObjectError + 1121, "CollectQuotedScalar", _
              "Unterminated quoted YAML scalar at end of file near line " & CStr(currentIndex + 1) & "."
End Function

Private Function NearestSection(ByRef sections() As String, ByVal childIndent As Long, _
                                ByRef sectionIndent As Long) As String
    Dim i As Long

    ' Zabbix 6.0 export uses indentationless sequences:
    '   items:
    '   - uuid: ...
    ' Therefore the list item can be at the SAME indentation as the key.
    For i = childIndent To LBound(sections) Step -1
        If Len(sections(i)) > 0 Then
            sectionIndent = i
            NearestSection = sections(i)
            Exit Function
        End If
    Next i

    sectionIndent = -1
    NearestSection = vbNullString
End Function

Private Function ObjectIndent(ByVal d As Object) As Long
    If d Is Nothing Then
        ObjectIndent = -1000
    ElseIf d.Exists("_indent") Then
        ObjectIndent = CLng(d("_indent"))
    Else
        ObjectIndent = -1000
    End If
End Function

Private Function RemoveBom(ByVal text As String) As String
    If Len(text) > 0 Then
        If AscW(Left$(text, 1)) = -2 Then       ' &HFEFF as signed
            RemoveBom = Mid$(text, 2)
            Exit Function
        End If
    End If
    RemoveBom = text
End Function

'============================================================
' Generic helpers
'============================================================

Private Function DGet(ByVal d As Object, ByVal key As String, ByVal defaultValue As String) As String
    If d Is Nothing Then
        DGet = defaultValue
    ElseIf d.Exists(key) Then
        DGet = CStr(d(key))
    Else
        DGet = defaultValue
    End If
End Function

Private Function DefaultIfBlank(ByVal value As String, ByVal defaultValue As String) As String
    If Len(value) = 0 Then
        DefaultIfBlank = defaultValue
    Else
        DefaultIfBlank = value
    End If
End Function

Private Function DashIfBlank(ByVal value As String) As String
    If Len(Trim$(value)) = 0 Then
        DashIfBlank = "-"
    Else
        DashIfBlank = value
    End If
End Function

' Normalize multi-line description for a single cell
Private Function CleanText(ByVal value As String) As String
    Dim s As String
    s = Replace(value, vbCrLf, vbLf)
    s = Replace(s, vbCr, vbLf)
    s = Replace(s, vbLf, vbLf)          ' keep line breaks (Alt+Enter in cell)
    s = Replace(s, vbTab, " ")
    CleanText = Trim$(s)
End Function

Private Function TriggerSignature(ByVal trig As Object) As String
    TriggerSignature = DGet(trig, "expression", vbNullString) & ChrW$(30) & _
                       DGet(trig, "name", vbNullString) & ChrW$(30) & _
                       DGet(trig, "priority", vbNullString) & ChrW$(30) & _
                       DGet(trig, "status", vbNullString)
End Function

